apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"gitlab","namespace":"mtstar-show"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ss-gitlab"}},"template":{"metadata":{"labels":{"app":"ss-gitlab"},"name":"ss-tp-gitlab","namespace":"mtstar-show"},"spec":{"containers":[{"env":[{"name":"GITLAB_ROOT_PASSWORD","value":"mt123456"},{"name":"GITLAB_HOST","value":"localhost"},{"name":"GITLAB_PORT","value":"80"},{"name":"GITLAB_SSH_PORT","value":"22"},{"name":"GITLAB_NOTIFY_ON_BROKEN_BUILDS","value":"true"},{"name":"TZ","value":"Asia/Shanghai"},{"name":"GITLAB_TIMEZONE","value":"Beijing"},{"name":"DB_TYPE","value":"postgres"},{"name":"DB_HOST","value":"postgresql"},{"name":"DB_PORT","value":"15432"},{"name":"DB_USER","value":"postgres"},{"name":"POSTGRES_PASSWORD","value":"123456"},{"name":"DB_NAME","value":"gitlab_production"},{"name":"REDIS_HOST","value":"redis"},{"name":"REDIS_PORT","value":"16379"}],"image":"gitlab/gitlab-ce:15.1.3-ce.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/","port":80},"initialDelaySeconds":180},"name":"ss-c-gitlab","ports":[{"containerPort":80,"name":"http"},{"containerPort":22,"name":"ssh"}],"readinessProbe":{"httpGet":{"path":"/","port":80},"initialDelaySeconds":120},"resources":{"limits":{"cpu":"1000m","memory":"5Gi"},"requests":{"cpu":"500m","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/etc/gitlab","name":"gitlab-config"},{"mountPath":"/var/log/gitlab","name":"gitlab-logs"},{"mountPath":"/var/opt/gitlab","name":"gitlab-datas"}]}],"volumes":[{"hostPath":{"path":"/data/ack-deploy/gitlab-component/gitlab-datas/config","type":"DirectoryOrCreate"},"name":"gitlab-config"},{"hostPath":{"path":"/data/ack-deploy/gitlab-component/gitlab-datas/logs","type":"DirectoryOrCreate"},"name":"gitlab-logs"},{"hostPath":{"path":"/data/ack-deploy/gitlab-component/gitlab-datas/data","type":"DirectoryOrCreate"},"name":"gitlab-datas"}]}}}}
  creationTimestamp: '2024-10-29T07:19:14Z'
  generation: 2
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
              'f:name': {}
              'f:namespace': {}
            'f:spec':
              'f:containers':
                'k:{"name":"ss-c-gitlab"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"DB_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DB_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DB_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DB_TYPE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DB_USER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GITLAB_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GITLAB_NOTIFY_ON_BROKEN_BUILDS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GITLAB_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GITLAB_ROOT_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GITLAB_SSH_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GITLAB_TIMEZONE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"POSTGRES_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"REDIS_HOST"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"REDIS_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":22,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":80,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/etc/gitlab"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/var/log/gitlab"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/var/opt/gitlab"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"gitlab-config"}':
                  .: {}
                  'f:hostPath':
                    .: {}
                    'f:path': {}
                    'f:type': {}
                  'f:name': {}
                'k:{"name":"gitlab-datas"}':
                  .: {}
                  'f:hostPath':
                    .: {}
                    'f:path': {}
                    'f:type': {}
                  'f:name': {}
                'k:{"name":"gitlab-logs"}':
                  .: {}
                  'f:hostPath':
                    .: {}
                    'f:path': {}
                    'f:type': {}
                  'f:name': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2024-10-29T07:19:14Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:redeploy-timestamp': {}
      manager: okhttp
      operation: Update
      time: '2024-10-29T08:02:20Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-10-29T08:02:55Z'
  name: gitlab
  namespace: mtstar-show
  resourceVersion: '126376754'
  uid: cdb2ebb8-5207-49a5-a933-762bf783fe9e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ss-gitlab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1730188940380'
      labels:
        app: ss-gitlab
      name: ss-tp-gitlab
      namespace: mtstar-show
    spec:
      containers:
        - env:
            - name: GITLAB_ROOT_PASSWORD
              value: mt123456
            - name: GITLAB_HOST
              value: localhost
            - name: GITLAB_PORT
              value: '80'
            - name: GITLAB_SSH_PORT
              value: '22'
            - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
              value: 'true'
            - name: TZ
              value: Asia/Shanghai
            - name: GITLAB_TIMEZONE
              value: Beijing
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: '15432'
            - name: DB_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: '123456'
            - name: DB_NAME
              value: gitlab_production
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '16379'
          image: 'gitlab/gitlab-ce:15.1.3-ce.0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ss-c-gitlab
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 22
              name: ssh
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '1'
              memory: 5Gi
            requests:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/gitlab
              name: gitlab-config
            - mountPath: /var/log/gitlab
              name: gitlab-logs
            - mountPath: /var/opt/gitlab
              name: gitlab-datas
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/ack-deploy/gitlab-component/gitlab-datas/config
            type: DirectoryOrCreate
          name: gitlab-config
        - hostPath:
            path: /data/ack-deploy/gitlab-component/gitlab-datas/logs
            type: DirectoryOrCreate
          name: gitlab-logs
        - hostPath:
            path: /data/ack-deploy/gitlab-component/gitlab-datas/data
            type: DirectoryOrCreate
          name: gitlab-datas
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-10-29T08:02:55Z'
      lastUpdateTime: '2024-10-29T08:02:55Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-10-29T07:19:14Z'
      lastUpdateTime: '2024-10-29T08:02:55Z'
      message: ReplicaSet "gitlab-79c7f54b76" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
