apiVersion: v1
kind: Service
metadata:
  name: postgres-internet
  namespace: default
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres