# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: pg-configmap
#   namespace: db
#   labels:
#     app: postgres
# data:
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: pg123456
#   POSTGRES_DB: postgres

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pg"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: db
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-internet
#   namespace: db
#   labels:
#     app: postgres
# spec:
#   ports:
#     - port: 5432
#       targetPort: 5432
#   type: ClusterIP
#   selector:
#     app: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-extranet
  namespace: db
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30012
  type: NodePort
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: pg
    app.kubernetes.io/name: postgresql
