apiVersion: v1
kind: Namespace
metadata:
  name: db

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: db
  labels:
    app: postgres
data:
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypass
  POSTGRES_DB: mydatabase

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: db
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: db
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-extranet
  namespace: db
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30002
  type: NodePort
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: db
spec:
  serviceName: "postgres-ss"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: registry.cn-shanghai.aliyuncs.com/nsmi/postgres:15.12-bookworm
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/run/postgresql
              name: pos
      volumes:
        - name: pos
          persistentVolumeClaim:
            claimName: postgres-pv-claim
