pg:
  outputs:

    dev:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [dev_username]
      pass: [dev_password]
      dbname: [dbname]
      schema: [dev_schema]

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

# company-name:
#   target: dev
#   outputs:
#     dev:
#       type: postgres
#       host: 172.17.0.1
#       user: user
#       password: admin123
#       port: 9002
#       dbname: smk # or database instead of dbname
#       schema: public
#       # threads: [optional, 1 or more]
#       [keepalives_idle](#keepalives_idle): 0 # default 0, indicating the system default. See below
#       connect_timeout: 10 # default 10 seconds
#       [retries](#retries): 2  # default 1 retry on error/timeout when opening connections
#       # [search_path](#search_path): [optional, override the default postgres search_path]
#       # [role](#role): [optional, set the role dbt assumes when executing queries]
#       # [sslmode](#sslmode): [optional, set the sslmode used to connect to the database]
#       # [sslcert](#sslcert): [optional, set the sslcert to control the certifcate file location]
#       # [sslkey](#sslkey): [optional, set the sslkey to control the location of the private key]
#       # [sslrootcert](#sslrootcert): [optional, set the sslrootcert config value to a new file path in order to customize the file location that contain root certificates]
  