apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: db
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-internet
#   namespace: db
#   labels:
#     app: redis
# spec:
#   ports:
#     - port: 6379
#       targetPort: 6379
#   type: ClusterIP
#   selector:
#     app: redis

# ---

apiVersion: v1
kind: Service
metadata:
  name: redis-extranet
  namespace: db
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 31779
  type: NodePort
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
