# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-internet
#   namespace: db
#   labels:
#     app: redis
# spec:
#   ports:
#     - port: 6379
#       targetPort: 6379
#   type: ClusterIP
#   selector:
#     app: redis

# ---

apiVersion: v1
kind: Service
metadata:
  name: redis-extranet
  namespace: db
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 31779
  type: NodePort
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
